version: '3.7'
services:
  mysql:
    container_name: management_mysql
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=management
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  php:
    container_name: management_php
    build: ./docker/php
    ports: ['9000:9001']
    links:
      - mysql
    volumes:
      - ./:/var/www/symfony:cached
  nginx:
    container_name: management_nginx
    build: ./docker/nginx
    ports: ['80:80']
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./:/var/www/symfony:cached
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - "xpack.security.enabled=false"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
    ports:
      - 9201:9200